service: awsWiki

package:
  exclude:
  - .circleci/**

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, "development"}
  region: us-west-2
  environment:
    PG_PORT: ${env:PG:PORT}
    PG_HOST: ${env:PG_HOST}
    PG_PASSWORD: ${env:PG_PASSWORD}
    PG_USER: ${env:PG_USER}

functions:
  getPageNotes:
    handler: functions/getPageNotes.handler
    events:
      - http:
          path: /documentation/{pageId}/notes
          method: get